#+LATEX_HEADER: \usepackage[vcentermath]{youngtab}
#+LATEX_HEADER: \usepackage{braket}
#+LATEX_HEADER: \newcommand{\bm}[1]{\mbox{\boldmath{$#1$}}}
* RGM 
** 9-Quark System
*** DineutronLambda System
**** Theoretic Concepts
1. A 9-Quart System can be divided into three baryon subsystem.
2. Each baryon system will be treated locally.
3. The interaction between each cluster remains unknown.
4. Complete set, Gaussian Functions will be adopted to describe interaction funct-
   ions.
5. To simplify our case, *color part* of wave function will be treated as three s-
   inglet wave functions.
6. Fully antisymmetrization should be applied to wave functions.
7. Wave function of center-of-mass system is added to transform wave functions in-
   to productions of single partical wave functions.
**** Complex Analysis
1. Wave function of a single baryon can be written as:
   \begin{equation}
   \psi(123)=\phi^{spatial}(123)\chi^{color}(123)\eta^{\sigma\cdot{}flavor}(123)\\
   \end{equation}
   Among which,\\
   \begin{eqnarray}
   \phi(123)&=&\phi(1)\phi(2)\phi(3)\\
   \phi(i)&=&(\frac{1}{\pi{}b^{2}})^{\frac{3}{4}}e^{-\frac{\bm{r}_i}{2b^2}}\\
   \chi(123)&=&\young(1,2,3)\quad\young(r,g,b)\\
   \eta^{\sigma\cdot{}flavor}&=&\frac{1}{\sqrt{2}}\left(\young(12,3)\quad
   \young(uu,d)\quad\young(12,3)\quad\young(\alpha\alpha,\beta)
   +\young(13,2)\quad\young(uu,d)\quad\young(13,2)\quad\young(\alpha\alpha,\beta)\right)
   \end{eqnarray}
2. Hamiltonian operator for single baryon can be written as:
   \begin{equation}
   H = \sum_{i}^{3}(m_i+\frac{\bm{p}^{2}_{i}}{2m_i})+\sum_{i>j=1}^{3}V_{i j}-T_{c.m}
   \end{equation}
   Among which,\\
   \begin{eqnarray}
   V_{i j} & = & V_{i j}^C + V_{i j}^G\\
   V_{i j}^C & = & -a_c\bm{\lambda_i}\cdot\bm{\lambda_j}\cdot\bm{r}_{i j}\\
   V_{i j}^G & = & \alpha_s\frac{\bm{\lambda_i}\cdot\bm{\lambda_j}}{4}\left[\frac{1}
   {|\bm{r}_{i j}|}-\frac{\pi}{2}\delta(\bm{r}_{i j})\left(\frac{1}{m_{i}^2}+\frac{1}{m_{j}^2}
   + \frac{4\bm{\sigma}_i\cdot\bm{\sigma}_j}{3m_{i}m_{j}}\right)\right]\\
   T_{c.m} & = & \frac{(\sum\limits_{i=1}^{3}\bm{p}_{i})^{2}}{2M_{total}}
   \end{eqnarray}
3. To simple our calculation, Jacobi's transformation is applied:
   \begin{eqnarray}
   \frac{\bm{r}_1+\bm{r}_2}{2}&=&\bm{R}\\
   \bm{r}_1-\bm{r}_2&=&\bm{r}_{1 2}\equiv\bm{r}
   \end{eqnarray}
   and then, we obtain,\\
   \begin{eqnarray}
   \bm{r}_{1}^{2}+\bm{r}_{2}^{2}&=&\frac{\bm{r}^2+4\bm{R}^2}{2}\\
   d\bm{r}_1{}d\bm{r}_2&=&d\bm{r}d\bm{R}
   \end{eqnarray}
4. Some matrix elements calculation steps are listed below:
   \begin{eqnarray}
   \bra{\phi(123)}\bm{r}_{1 2}\ket{\phi(123)}&=&\bra{\phi(1)\phi(2)}\bm{r}_{1 2}\ket{\phi(1)\phi(2)}\\
   & = & \left(\frac{1}{\pi{}b^2}\right)^3\int\int
   \end{eqnarray}
   